FROM ruby:3.4.2-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    dos2unix \
    git \
    libvips \
    libyaml-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

COPY Gemfile ./
RUN bundle install

COPY . .

RUN dos2unix bin/* && chmod +x bin/*

EXPOSE 8000

CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "8000"] 